project:
  output-dir: docs
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Main page"
        href: index.qmd
      - text: "About organizers"
        href: Handbook/Organizers.qmd

      - section: "Dataset A: Balance Corpus"
        contents:
          - Datasets/BalanceCorpus/scripts/general_data_loading_cheatsheet/BalanceCorpusCheatSheet.qmd

          - section: "Processing: Acoustics"
            contents:
              - Datasets/BalanceCorpus/scripts/continuousacoustics/Processing_acoustics.ipynb
              - Datasets/BalanceCorpus/scripts/continuousacoustics/Speaker_diarization.ipynb
              - "Open Smile"
          - section: "Processing: Motion tracking"
            contents:
              - Datasets/BalanceCorpus/scripts/motiontracking/Masking_Mediapiping.ipynb
              - Datasets/BalanceCorpus/scripts/openface/OpenFace_analysis.ipynb
          - section: "NLP Methods"
            contents:
              - Datasets/BalanceCorpus/scripts/nlp_taboo/NLP_overview.ipynb
              - Datasets/BalanceCorpus/scripts/nlp_taboo/00_dataset_preview.ipynb
              - Datasets/BalanceCorpus/scripts/nlp_taboo/01_audio_to_transcripts.ipynb
              - Datasets/BalanceCorpus/scripts/nlp_taboo/02_semantic_homing.ipynb
              - Datasets/BalanceCorpus/scripts/nlp_taboo/03_leyical_alignment.ipynb
          - section: "Gesture Classification"
            contents:
              - Datasets/BalanceCorpus/scripts/usingenvisionhgdetector/envisionhgdetector.ipynb
          - section: "Merging streams"
            contents:
              - Datasets/BalanceCorpus/scripts/merging/Merging-modalities-mockscript.qmd

      - section: "Dataset B: PARSEL"
        contents:
          - Datasets/PARSEL/scripts/general_data_loading_cheatsheet/PARSELCheatSheet.qmd

          - section: "Processing: Acoustics"
            contents:
              - Datasets/PARSEL/scripts/continuousacoustics/Processing_acoustics.ipynb
              - Datasets/PARSEL/scripts/continuousacoustics/Speaker_diarization.ipynb
              - "Open Smile"
      
      - section: "Analyses & Tools"
        contents:
          - section: "Alex Paxton: State of the Art Multimodal Analysis (ALIGN R package)"
            contents:
              - "tba"
          - section: "Wim Pouw: Intrapersonal Coupling Using Empirical Mode Decomposition"
            contents:
              - Datasets/BalanceCorpus/scripts/analysis_multiscaleintracoupling/envelope_emd_demo.ipynb
              - Datasets/BalanceCorpus/scripts/analysis_multiscaleintracoupling/preprocessing.ipynb
              - Datasets/BalanceCorpus/scripts/analysis_multiscaleintracoupling/analysis.ipynb
          - section: "Travis Wiltshire: Multiscale Methods (WMS)"
            contents:
              - wednesday-coordination/wms_exercises.qmd
          - section: "Annie Bryant: Multi-Scale Dynamical Approach in Brain Signals"
            contents:
              - "tba"
          - section: "Babajide Owoyele: Masking Audio and Video"
            contents:
              - thursday-masking/notebooks/audio_deidentification.ipynb
              - thursday-masking/notebooks/masking-lite.ipynb

      - section: "Group Projects"
        contents:
          - group-projects\MDIG2026_group_projects.md
          - group-projects\Groups_overview.qmd

  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/WimPouw/TilburgMultiscaleSummerschool2026


metadata:
  crossref:
    chapters: true

theme: united

format:
  html:
    theme: journal
    toc: true
    fontsize: 12px
    max-width: 8000px
    toc-location: right
    toc-title: "Contents"
    toc-depth: 3
    number-sections: false
    code-fold: false
    code-tools: true
    css: |
      .quarto-container {
        max-width: 8000px !important;
      }
      body {
        font-size: 10px;
      }

execute:
  freeze: false
  warning: false
  message: false
  cache: false   
